services:
    faststicker-tgbot:
        image: ghcr.io/okiscape/faststicker-tgbot:latest
        restart: unless-stopped
        container_name: faststicker-tgbot
        env_file: .env
        volumes:
            - ./utils:/app/utils
